### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/maintenance#240]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] base_maintenance - By @FernandoRomera - #266
- [x] base_maintenance_config - By @victoralmau - #431
- [x] base_maintenance_group - By @Borruso - #344
- [x] maintenace_request_purchase - By @AnizR - #393
- [x] maintenance_account - By @victoralmau - #381
- [x] maintenance_equipment_contract - By @Borruso - #343
- [x] maintenance_equipment_hierarchy - By @FrancoMaxime - #241
- [x] maintenance_equipment_image - By @FrancoMaxime - #284
- [ ] maintenance_equipment_sequence
- [x] maintenance_equipment_status - By @aleuffre - #341
- [x] maintenance_equipment_tags - By @kaynnan - #345
- [x] maintenance_equipment_usage - By @victoralmau - #384
- [x] maintenance_location - By @IT-Ideas - #389
- [x] maintenance_plan - By @alexeirivera87 - #339
- [x] maintenance_plan_activity - By @luisDIXMIT - #392
- [x] maintenance_product - By @kaynnan - #342
- [x] maintenance_project - By @dalonsod - #338
- [x] maintenance_purchase - By @IT-Ideas - #388
- [x] maintenance_request_repair - By @kaynnan - #323
- [x] maintenance_request_sequence - By @Christian-RB - #340
- [x] maintenance_request_stage_transition - By @kaynnan - #346
- [x] maintenance_security - By @carolinafernandez-tecnativa - #373
- [x] maintenance_team_hierarchy - By @kaynnan - #349
- [x] maintenance_timesheet_time_control - By @victoralmau - #385

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by Borruso** [comment]
`maintenance_equipment_contract` #343

**Comment by Borruso** [comment]
`base_maintenance_group` #344

**Comment by kaynnan** [comment]
`maintenance_request_repair` #323
