### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/maintenance#7]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] account_asset_maintenance
- [x] base_maintenance_config
- [x] maintenance_equipment_scrap - By @dalonsod - #13 
- [x] maintenance_plan - ~~By @bestmazzo - #11~~ - By @dalonsod - #12

**Comment by dalonsod** [comment]
@pedrobaeza I'll migrate `maintenance_equipment_scrap`

**Comment by astirpe** [comment]
While porting `base_maintenance_config` to V11,  I'm splitting it in two different modules:

- `base_maintenance_config` #21 , containing only the general configuration view;
- `base_maintenance_group` #22 , containing all the stuff related the newly added groups.

**Comment by etobella** [comment]
I think it is time to close this issue
